# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d34a690671d33659dac634379d73e20840ecf3eb7f3a6032101d4e2cf7e07521dbcb83742fd8a92381d50fc47344ade34bb6c73e6b4a1ea3125e88ea0120497f

test:
  secret_key_base: 0ecda531581a4c4224161e47f15bda9b5fe11ed6d77617459b8737ae712b7244d1585d4f4261eb785765bf91125a8c8f5d0925388b87f14dc3c7bbc68e436e86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
